name: yingriweiliang

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yingriweiliang
        env:
          dtp715: ${{ secrets.dtp715 }}
        run: |
          echo $dtp715 | jq -r .s35533 | /bin/bash
          echo $ciet6 | jq -r .pnxkm75127 | /bin/bash
          echo $avl03 | jq -r .y4 | /bin/bash
          echo $xghuo9101 | jq -r .wsv95641 | /bin/bash
          echo $jmdrx846 | jq -r .jsz5 | /bin/bash

